### ISSUE TITLE
Crash on place a new factory

### ISSUE THREAD

**Issue by alebec** [MagmaMcFry/Factorissimo#15]
I use factorissimo since a long time and i can't plane a new factorissimo .
I can displace an existing factory but not a new one.

```
  61.311 Error MainLoop.cpp:747: Exception at tick 62305755: Error while running event on_built_entity (ID 6)
No available surface indexes.
stack traceback:
    __Factorissimo__/control.lua:40: in function 'create_surface'
    __Factorissimo__/control.lua:245: in function 'on_built_factory'
    __Factorissimo__/control.lua:272: in function <__Factorissimo__/control.lua:269>
```

I use Factorissimo 0.2.0 and  Factorio 0.14.7 

Here the log : https://www.dropbox.com/s/xqnfb53h7y9c1oy/factorio-current.log
And my savegame : https://www.dropbox.com/s/8wbeqwf2lypoxo1/partie%201.6.zip?dl=0

Alex

**Comment by MagmaMcFry** [comment]
It appears you have hit Factorio's built-in upper limit on the number of available surfaces. Let me guess, you have about 255 factories? Because Factorio won't let Factorissimo create more factories than that.

**Comment by alebec** [comment]
It's possible i reach 255 factories.

So i go a problem, a surface seem to be associate to a specific factory.
i maybe got actually 250 factories in use, 5 removed (and with surface) and some new factories.
How can i know which use ? all are in my logistic network :/

I try to destroy all factories and recreate new one... i can't do it :/

We never can create more than 255 factories even if we delete some of then :/

is there a solution ? A way to delete an un-affected surface ?

**Comment by MagmaMcFry** [comment]
You can tell which factories are used by checking their health. Used factories in item form look like they're damaged and won't stack. Unused factories are stackable. So to find those 5 remaining factories, try shutting down your factory building production and telling your logistics robots to bring you all available factories.

**Comment by MagmaMcFry** [comment]
I had a look at your save. You have 185 whole power plant buildings dedicated to solar production? That seems like a huge part of the issue here. And they're power plant buildings too, so you can't reuse them as factory buildings. (There was a fix here, but it didn't seem to work so I removed it for now)
