### ISSUE TITLE
Game exists to main menu on placing first factory

### ISSUE THREAD

**Issue by smaitlx** [MagmaMcFry/Factorissimo#25]
When placing the very first factory crafted, the game quits to the main menu with the following error:

Error while running event
Factorissimi2::on_built_entity(ID 6)
Unknown tile name: out-of-factory
Stack traceback:
__Factorissimo2__/control.lua:459: in function 'create_factory_interior'
__Factorissimo2__/control.lua:736; in function __Factorissimo2__/control.lua:729

**Comment by MagmaMcFry** [comment]
First of all, wrong repository, this is the Factorissimo1 source.

Second, this is not a bug with Factorissimo2. Unfortunately Factorio only supports 256 different floor tile types, which all mods have to share with each other and with the base game. To avoid crashing on startup, some other mod that adds lots of floor tiles decided to delete Factorissimo2's tiles to make room for its own. Now of course factory buildings can't be built without floors, so Factorissimo2 crashed. Not cool, right?
