### ISSUE TITLE
Rocket launches to space

### ISSUE THREAD

**Issue by DanHarty** [MagmaMcFry/Factorissimo#6]
I'm impressed that this mod can already do real-time instancing.

I propose a version where you a rocket launch to get to the moon of whatever planet Factorio is set on. It would be an instance just like the inside of a factory. Resources would be expensive to send up, but cheap to send down.

Mainly here to ask about the technical feasibility of this idea. How large can factories be? Could entirely different terrain be generated inside of one?

**Comment by MagmaMcFry** [comment]
For factories I'm using the [Surface API](http://lua-api.factorio.com/latest/LuaSurface.html) to create a new surface for every factory. Note that the overworld is a surface too, so clearly there aren't that many limitations to what you can do with them. Yes, your idea is very feasible, after all it is exactly the original intended purpose of the Surface API.
